catalog_name: mlops_students
schema_name: jarb8926

parameters:
  n_estimators: 1000
  max_depth: 6

num_features:
  - age
  - duration
  - campaign
  - pdays
  - previous
  - emp.var.rate
  - cons.price.idx
  - cons.conf.idx
  - euribor3m
  - nr.employed

cat_features:
  - job
  - marital
  - education
  - default
  - housing
  - loan
  - contact
  - month
  - day_of_week
  - poutcome

target: y